name: Waka Readme

on:
  schedule:
    # Runs at 12am UTC
    - cron: "* * * * *"

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPOSITORY: <thomas-yanxin/thomas-yanxin> # optional, By default, it will automatically use the repository who's executing the workflow.
